server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

app:
  webhook:
    token: ${WEBHOOK_TOKEN:CHANGEME}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:events}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true
