apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-webhook-receiver.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "argocd-webhook-receiver.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "argocd-webhook-receiver.name" . }}
    spec:
      containers:
        - name: receiver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: LOG_LEVEL
              value: {{ .Values.config.LOG_LEVEL | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}