apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.argocd-events-receiver: |
    url: http://argocd-events-receiver.default.svc.cluster.local:8080/webhook/argocd
    headers:
      X-Token: $webhook.token

  template.sync-event: |
    message: |
      {
        "appName": "{{.app.metadata.name}}",
        "project": "{{.app.spec.project}}",
        "revision": "{{.app.status.sync.revision}}",
        "status": "{{.app.status.sync.status}}",
        "syncStartedAt": "{{.app.status.operationState.startedAt}}",
        "syncCompletedAt": "{{.app.status.operationState.finishedAt}}",
        "images": {{ toJson .app.status.summary.images }}
      }

  trigger.on-sync: |
    - when: app.status.operationState.phase in ['Succeeded', 'Failed']
      send: [argocd-events-receiver]
      template: sync-event